---
- name: Perform general server setup
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Gather allowed firewall ports based on groups
      ansible.builtin.set_fact:
        firewall_allowed_tcp_ports: "{{ firewall_allowed_tcp_ports + lookup('vars', item) }}"
      loop: "{{ lookup('varnames', '.*__firewall_ports').split(',') }}"
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
  roles:
    - saiba-tenpura.common
    - geerlingguy.security
    - saiba-tenpura.firewall

- name: Setup docker hosts
  hosts: docker_hosts
  roles:
    - geerlingguy.docker

- name: Setup mail whales
  hosts: mailwhales
  roles:
    - saiba-tenpura.docker-mailserver
