---
roles:
  - name: geerlingguy.docker
    version: 8.0.0
  - name: geerlingguy.security
    version: 3.0.0
  - name: saiba-tenpura.common
    src: https://github.com/saiba-tenpura/ansible-role-common.git
    scm: git
    version: main
  - name: saiba-tenpura.docker-mailserver
    src: https://github.com/saiba-tenpura/ansible-role-docker-mailserver.git
    scm: git
    version: main
  - name: saiba-tenpura.firewall
    src: https://github.com/saiba-tenpura/ansible-role-firewall.git
    scm: git
    version: custom

collections:
  - name: ansible.posix
  - name: community.docker
    version: ">=3.6.0"
