---
roles:
  - name: geerlingguy.docker
  - name: geerlingguy.security
  - name: saiba-tenpura.firewall
    src: https://github.com/saiba-tenpura/ansible-role-firewall.git
    scm: git
    version: custom
