---
main_ssh_port: 22
main_system_user: saiba

security_ssh_port: '{{ main_ssh_port }}'
security_ssh_allowed_users:
  - '{{ main_system_user }}'
security_sudoers_passworded:
  - '{{ main_system_user }}'
security_autoupdate_enabled: false

firewall_allowed_tcp_ports:
  - '{{ main_ssh_port }}'
